### ISSUE TITLE
Form mobile version and desktop version

### ISSUE THREAD

**Issue by omar25ahmed** [awaisanwar544/portfolio#5]
## suggestions
- [x] for the forms you can put to the each version a form and give it display: none in the other version to be able to submit

**Comment by franciscoPonceDev** [comment]
You can also use just one input for full name in both versions instead of different inputs in each version.

**Comment by 41hulk** [comment]
- [ ] Remember to create different formspree project for mobile and desktop

**Comment by awaisanwar544** [comment]
Thanks, guys for your valuable suggestions. @omar25ahmed solution has worked fine.

> ## suggestions
> * [x]  for the forms you can put to the each version a form and give it display: none in the other version to be able to submit
